_format_version: "2.1"
_transform: true

services:
- name: test-server
  url: http://MYIP:8088
  routes:
   - name: test-route
     strip_path: false
     paths:
      - /test
     plugins:
        - name: pre-function
          config:
            access: 
            - | 
              local raw_body = kong.request.get_raw_body()
              if raw_body then
                local updated_body = raw_body:gsub("Sept", "Sep")
                kong.service.request.set_raw_body(updated_body)
              end
    
    # This route IS rate-limited to 5 requests per minute.
   - name: limited-route
     paths:
     - /limited
     strip_path: false
     plugins:
     - name: rate-limiting
       config:
         second: 2
         policy: local # 'local' policy stores counters in memory on each node

    # This route has NO rate limit applied.
   - name: unlimited-route
     paths:
     - /unlimited
     strip_path: false

